# https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html
Vagrant.require_version '>= 2.0.0'

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  # set up ports to webserver
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8061, host: 8061

  # install docker
  config.vm.provision "shell",
    inline: "apt-get -y install python-docker docker.io"

  config.vm.define "machine1"
  config.vm.provision "ansible" do |ansible|
    # https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "webservers" => ["machine1"],
      "group2" => ["machine2"],
      "all_groups:children" => ["group1", "group2"],
      "group1:vars" => {"variable1" => 9,
                        "variable2" => "example"}
    }
  end
end
